# Generated by Django 5.0.6 on 2024-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Samochod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.PositiveSmallIntegerField()),
                (
                    "gearbox",
                    models.CharField(
                        choices=[("AUTOMATIC", "automatic"), ("MANUAL", "manual")],
                        max_length=16,
                    ),
                ),
                ("active_cruise_control", models.BooleanField(default=False)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("SEDAN", "sedan"),
                            ("WAGON", "wagon"),
                            ("HATCHBACK", "hatchback"),
                            ("SUV", "SUV"),
                            ("VAN", "van"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
