# Generated by Django 5.0.6 on 2024-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="samochod",
            name="fuel_type",
            field=models.CharField(
                choices=[("GASOLINE", "gasoline"), ("DIESEL", "diesel")],
                default="GASOLINE",
                max_length=16,
            ),
        ),
    ]
