# Generated by Django 5.0.6 on 2024-05-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_samochod_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="samochod",
            name="luggage_capacity",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="samochod",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("GASOLINE", "gasoline"),
                    ("DIESEL", "diesel"),
                    ("ELECTRIC", "electric"),
                ],
                default="GASOLINE",
                max_length=16,
            ),
        ),
    ]
