# Generated by Django 5.0.6 on 2024-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_samochod_air_conditioning_samochod_segment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="samochod",
            options={"verbose_name": "Samochód", "verbose_name_plural": "Samochody"},
        ),
        migrations.AddField(
            model_name="samochod",
            name="make",
            field=models.CharField(default="", max_length=255, verbose_name="Make"),
        ),
        migrations.AddField(
            model_name="samochod",
            name="model",
            field=models.CharField(default="", max_length=255, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="samochod",
            name="segment",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("S", "S"),
                    ("M", "M"),
                    ("J", "J"),
                ],
                default="A",
                max_length=16,
            ),
        ),
    ]
