# Generated by Django 5.0.6 on 2024-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_alter_samochod_make_alter_samochod_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Klient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=16)),
                ("birthday", models.DateTimeField()),
            ],
        ),
    ]
