# Generated by Django 5.0.6 on 2024-05-30 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0008_alter_klient_options_klient_driving_license_since_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="klient",
            name="name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="klient",
            name="surname",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="klient",
            name="driving_license_since",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
