# Generated by Django 5.0.6 on 2024-05-31 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0010_rezerwacja"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rezerwacja",
            options={"verbose_name": "Rezerwacja", "verbose_name_plural": "Rezerwacje"},
        ),
    ]
